services:
  gfc-d-bot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - DISCORD_ADMIN_ROLE=${DISCORD_ADMIN_ROLE}
      - DISCORD_GUILD_ID=${DISCORD_GUILD_ID}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
    restart: unless-stopped
